language: python

dist: xenial

sudo: true

matrix:
  include:
    - os: linux
      python: 2.7
      env: BUILD_PYTHONNET="false"
    - os: linux
      python: 3.5
      env: BUILD_PYTHONNET="false"
    - os: linux
      python: 3.6
      env: BUILD_PYTHONNET="false"
    - os: linux
      python: 3.7
      env: BUILD_PYTHONNET="false"
    - os: linux
      python: 3.8
      env: BUILD_PYTHONNET="true"
#    - os: osx
#      language: generic
#      env: PYTHON=2.7.17
#    - os: osx
#      language: generic
#      env: PYTHON=3.5.9
#    - os: osx
#      language: generic
#      env: PYTHON=3.6.10
#    - os: osx
#      language: generic
#      env: PYTHON=3.7.6
#    # wait for pythonnet to support Python 3.8
#    # - os: osx
#    #   language: generic
#    #   env: PYTHON=3.8.1

addons:
  apt:
    sources:
      - sourceline: deb https://download.mono-project.com/repo/ubuntu stable-xenial/snapshots/5.20 main
        key_url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA6A19B38D3D831EF
    packages:
      - mono-devel
      - ca-certificates-mono

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update
      brew outdated pyenv || brew upgrade pyenv
      brew install pyenv-virtualenv gcc pkg-config glib mono
      brew cask install java
      pyenv install --list
      pyenv install $PYTHON
      export PYENV_VERSION=$PYTHON
      pyenv virtualenv venv
      source /Users/travis/.pyenv/versions/${PYTHON}/envs/venv/bin/activate
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt update
      sudo apt install software-properties-common build-essential g++ gcc-multilib g++-multilib gfortran libgfortran3:i386 zlib1g:i386 net-tools default-jre -y
      sudo apt install libglib2.0-dev clang python3-pip python3-dev -y
    fi

install:
  - mono --version
  - java --version
  - python --version
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade setuptools wheel
  - python -m pip install pycparser
  - |
    if [ "$BUILD_PYTHONNET" == "true" ]; then
      git clone https://github.com/pythonnet/pythonnet.git
      sed -i 's/if not enable_shared:/#if not enable_shared:/' pythonnet/setup.py
      sed -i 's/defines.append("PYTHON_WITHOUT_ENABLE_SHARED")/#defines.append("PYTHON_WITHOUT_ENABLE_SHARED")/' pythonnet/setup.py
      python setup.py bdist_wheel
      python -m pip install --no-index --find-links=./pythonnet/dist/ pythonnet
      rm -rf pythonnet
    fi
  - |
    if [ "$BUILD_PYTHONNET" == "false" ]; then
      python -m pip install pythonnet
    fi

script:
  - python setup.py tests
